### ISSUE TITLE
RBAC collector removes labels from labels configMap

### ISSUE THREAD

**Issue by smauermann** [gepaplexx/multena-rbac-collector#20]
When RBAC collector updates the labels configMap, existing labels are removed. We create the configMap via ArgoCD and this attaches the following label to the cm:
```yaml
metadata:
  labels:
    argocd.argoproj.io/instance: multena
```
So after every RBAC collector run we are seeing a diff in ArgoCD.

Ideally, any existing labels/annotations should be preserved during an update of the cm.
